<?php
/**
 * @file
 *   Hosting CiviCRM API functions.
 */

/**
 * Return the number of sites where CiviCRM is available
 */
function hosting_civicrm_site_count() {
  $platforms = hosting_civicrm_get_platforms();

  $count = 0;
  foreach ($platforms as $key => $nid) {
    $count += hosting_site_count($nid);
  }

  return $count;
}

/**
 * Return an array of platforms that contain CiviCRM
 */
function hosting_civicrm_get_platforms() {
  //TODO: cache the result
  $package_id = db_result(db_query('SELECT nid FROM {hosting_package} WHERE short_name = "%s"', 'civicrm'));
  $result = db_query('SELECT nid FROM {hosting_platform} pl JOIN {hosting_package_instance} pkg ON pl.nid=pkg.rid WHERE pkg.package_id=%d', $package_id);

  $platforms = array();
  while ($nid = db_result($result)) {
    $platforms[] = $nid;
  }
  return $platforms;
}

/**
 * Return an array of enabled sites capable of running CiviCRM
 *
 * @param $order_by
 *   Field to order the returned sites by.
 */
function hosting_civicrm_get_sites($order_by = null) {
  $platforms = hosting_civicrm_get_platforms();
  $sites = array();

  foreach ($platforms as $platform) {
    //get all the enabled sites on the platform
    if (isset($order_by)) {
      $result = db_query('SELECT n.nid FROM {node} n LEFT JOIN {hosting_site} s ON n.nid=s.nid WHERE n.type="site" and s.status = %d and s.platform = %d ORDER BY "%s" ASC', HOSTING_SITE_ENABLED, $platform, $order_by);
    }
    else {
      $result = db_query('SELECT n.nid FROM {node} n LEFT JOIN {hosting_site} s ON n.nid=s.nid WHERE n.type="site" and s.status = %d and s.platform=%d', HOSTING_SITE_ENABLED, $platform);
    }
    while ($nid = db_fetch_object($result)->nid) {
      $sites[] = $nid;
    }
  }

  return $sites;
}
